2025-04-08 15:46:42   main.py --matcher master --max_num_keypoints 2048 --img_size 512 --data_dir data --log_dir out_sift-lg --save_images --device cuda
2025-04-08 15:46:42   Arguments: Namespace(matcher='master', max_num_keypoints=2048, num_iterations=4, img_size=512, save_images=True, device='cuda', data_dir='data', log_dir='out_sift-lg')
2025-04-08 15:46:42   The outputs are being saved in logs/out_sift-lg/2025-04-08_15-46-42
2025-04-08 15:46:42   
Traceback (most recent call last):
  File "/gpfs/home3/scur2410/EarthMatch_Master_Duster/main.py", line 51, in <module>
    matcher = get_matcher(args.matcher, device=args.device, max_num_keypoints=args.max_num_keypoints)
  File "/gpfs/home3/scur2410/EarthMatch_Master_Duster/image-matching-models/matching/utils.py", line 158, in wrapper
    return func(*a, **ka)
  File "/gpfs/home3/scur2410/EarthMatch_Master_Duster/image-matching-models/matching/__init__.py", line 221, in get_matcher
    from matching.im_models import master
  File "/gpfs/home3/scur2410/EarthMatch_Master_Duster/image-matching-models/matching/im_models/master.py", line 11, in <module>
    from mast3r.model import AsymmetricMASt3R
ModuleNotFoundError: No module named 'mast3r'

